/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2015-01-27 21:27:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<!--\n");
      out.write("To change this license header, choose License Headers in Project Properties.\n");
      out.write("To change this template file, choose Tools | Templates\n");
      out.write("and open the template in the editor.\n");
      out.write("-->\n");
      out.write("<html lang=\"es\">\n");
      out.write("            \n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/ChatStyle.css\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/animate.css\">\n");
      out.write("        <link href='http://fonts.googleapis.com/css?family=Permanent+Marker' rel='stylesheet' type='text/css'>\n");
      out.write("        <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>\n");
      out.write("        <title>DeadPool's Chat</title>\n");
      out.write("     </head>\n");
      out.write("            \n");
      out.write("     <body>\n");
      out.write("         <div class=\"col-md-3 center-block quitar-float text-center espacio-arriba\">   \n");
      out.write("            <img src=\"img/logoDeadpool.png\"class='animated bounceIn'>\n");
      out.write("            <h1 class='Permanent-Marker grande negro animated fadeIn retraso-1'>DeadPool's Chat</h1>\n");
      out.write("            <div class='animated fadeInDown retraso-2'>\n");
      out.write("            <form method=\"post\" action=\"Login.do\" >\n");
      out.write("                <p>\n");
      out.write("                  <label class='blanco'>Nombre:</label>\n");
      out.write("                  <input type=\"text\" name=\"miNick\" />\n");
      out.write("                  </p>\n");
      out.write("                <input type=\"submit\" name=\"entrar\" value=\"Entrar\"/>\n");
      out.write("            </form>\n");
      out.write("            </div>\n");
      out.write("          </div> \n");
      out.write("         \n");
      out.write("         <div class=\"col-md-5 center-block text-center quitar-float espacio-arriba\">\n");
      out.write("            <h2>Cliente/Servidor</h2>\n");
      out.write("            <table>\n");
      out.write("                <tr>\n");
      out.write("                  <td>Catedratico:</td>\n");
      out.write("                  <td>Equipo:</td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                  <td class='espacio-derecha'>Dr. Juan Carlos López Pimentel.</td>\n");
      out.write("                  <td>Marlon Antonio Aguilar Castillo.</td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td></td>\n");
      out.write("                <td>Dagoberto Marroquin Tepale.</td>\n");
      out.write("                </tr>\n");
      out.write("            </table>\n");
      out.write("         </div>\n");
      out.write("                \n");
      out.write("     \n");
      out.write("     </body>\n");
      out.write("</html>    ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
