/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2015-03-10 17:12:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ChatRoom_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

 String User;
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');

    if(session.getAttribute("user")==null){
       response.sendRedirect("index.jsp");
   }else{
     User = (String)session.getAttribute("user");
   }

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        \n");
      out.write("        <link rel=\"stylesheet\" href=\"css/Mak.css\" type=\"text/css\"/>\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/addDelete.css\" type=\"text/css\"/>\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/chatRequest.css\" type=\"text/css\"/>\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/User.css\" type=\"text/css\"/>\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/demo.css\"/>\n");
      out.write("        \n");
      out.write("        <link rel=\"stylesheet\" href=\"css/chat.css\" type=\"text/css\"/>\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/screen.css\" type=\"text/css\"/>\n");
      out.write("        \n");
      out.write("        <link rel=\"stylesheet\" href=\"css/windowsSelec.css\" type=\"text/css\"/>\n");
      out.write("        \n");
      out.write("        <link href='http://fonts.googleapis.com/css?family=Permanent+Marker' rel='stylesheet' type='text/css'>\n");
      out.write("        <link href='http://fonts.googleapis.com/css?family=Orbitron:400,700' rel='stylesheet' type='text/css'>\n");
      out.write("        <script src=\"js/jquery.min.js\"></script>\n");
      out.write("        \n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>DeadPool's Chat</title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <div id=\"contenedor\">\n");
      out.write("            <div id=\"bajar\">Hi! ");
      out.print(User);
      out.write(" Welcome.</div>\n");
      out.write("            <div id=\"cabecera\" class=\"Permanent-Marker letraGrande rojo\"><label id=\"Titulo\">DeadPool's Chat</label></div>\n");
      out.write("            <div id=\"contenedor2\" class=\"effect1\">\n");
      out.write("                <div id=\"contUsuarios\">\n");
      out.write("                    <div id=\"TiUsuarios\" class='rojoAnegro letraBlanca letraTitulo Permanent-Marker bordeNegro'>Users</div>\n");
      out.write("                    <div class=\"rojoOscuro bordeContorno\" id=\"divUsers\">\n");
      out.write("                                                \n");
      out.write("                    </div>\n");
      out.write("                    <p id=\"botonera2\"><input id=\"button1\" class=\"inputW2\" type=\"button\" onclick=\"createSelecChat()\" value=\"Create chat group\"></p>\n");
      out.write("                </div>\n");
      out.write("                <div id=\"contChat\">\n");
      out.write("                    <div id=\"TiChat\" class='rojoAnegro letraBlanca letraTitulo Permanent-Marker bordeNegro'>General Chat</div>\n");
      out.write("                    <div class=\"blanco general\" id=\"divChat\"></div>\n");
      out.write("                    <div id='botonera'  >\n");
      out.write("                     <input id=\"MG\" class=\"inputM\"  type=\"text\" placeholder=\"You're Message\">\n");
      out.write("                     <input onclick=\"saveValue(document.getElementById('MG').value);\" class=\"inputW\" type=\"button\"  value=\"Send\">\n");
      out.write("                     </div>\n");
      out.write("                  <!--  <div id=\"textarea\" contenteditable></div><div id=\"btnenviar\">Enviar</div>-->\n");
      out.write("                </div>\n");
      out.write("                <div id=\"contInvitation\">\n");
      out.write("                    <div id=\"TiInvitation\" class='rojoAnegro letraBlanca letraTitulo Permanent-Marker bordeNegro'>Invitations</div>\n");
      out.write("                    <div id=\"divInvitation\" class=\"rojoOscuro\"></div>\n");
      out.write("                    <div id=\"TiInvitation\" class='rojoAnegro letraBlanca letraTitulo Permanent-Marker bordeNegro'>Chat Requests</div>\n");
      out.write("                    <div id=\"divRequest\" class=\"rojoOscuro\"></div>\n");
      out.write("                    <input type=\"button\"  id=\"button2\" onclick=\"createSelecChatReq()\" class=\"inputR\" value=\"Create chat request\" />\n");
      out.write("                    \n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("        </div>  \n");
      out.write("            \n");
      out.write("           <!-- Create Conversation--> \n");
      out.write("            <div class=\"overlay-container\">\n");
      out.write("\t\t<div class=\"window-container zoomin\">\n");
      out.write("\t\t\t <form class=\"PotentialMates bordeNegro\" action=\"createConversation.do\" method=\"post\">\n");
      out.write("                         <div class=\"letraCentrada rojoAnegro letraBlanca letraTitulo Permanent-Marker bordeNegro\">Select your friends</div>\n");
      out.write("                         <div id=\"areaUsers\" class=\"AreaMates\">\n");
      out.write("                           \n");
      out.write("                         </div>\n");
      out.write("                         <div id=\"botoneraSelec\">\n");
      out.write("                             <input type=\"text\" name=\"namechat\" class=\"input3\" maxlength=\"10\" onkeydown=\"return alphaOnly(event)\" placeholder=\"Chat Name\" required=\"true\"/>\n");
      out.write("                         <input type=\"submit\" class=\"BtnMates\"  value=\"Create\"/>\n");
      out.write("                         <input type=\"reset\" class=\"BtnMates\"  value=\"Reset\"/>\n");
      out.write("                         <input type=\"button\" class=\"newclose\"  value=\"Close\"/>\n");
      out.write("                         </div>\n");
      out.write("                        </form>\n");
      out.write("\t\t</div>\n");
      out.write("            </div>\n");
      out.write("           <!-- Finish Create Conversation--->\n");
      out.write("            <!-- create options--->  \n");
      out.write("            <div class=\"overlay-contaoption\">\n");
      out.write("\t\t<div class=\"window-containeroption zoomin\">\n");
      out.write("                    <div id=\"Options\">\n");
      out.write("                        \n");
      out.write("                    </div>\n");
      out.write("\t\t</div> \n");
      out.write("            </div>\n");
      out.write("           <!--- Fin create options -->\n");
      out.write("           <!-- create chat request -->\n");
      out.write("           <div class=\"overlay-chatreq\">\n");
      out.write("\t\t<div class=\"window-chatreq zoomin\">\n");
      out.write("                        <div class=\"styleChatR bordeNegro\" >\n");
      out.write("                        <div class=\"letraCentrada rojoAnegro letraBlanca letraTitulo Permanent-Marker bordeNegro\">Select the Chat<a class=\"closeChatR\" href=\"javascript:void(0)\">X</a></div>\n");
      out.write("                        <form class=\"formRequest\" action=\"sendChatRequest.do\" method=\"POST\">\n");
      out.write("                        <div id=\"areaChats\" class=\"bordeNegro\"></div>\n");
      out.write("                        <div class=\"btnrequest\" >\n");
      out.write("                        <input type=\"submit\" class=\"btnAddDelete\"  value=\"Send Chat Request\"/>\n");
      out.write("                        <input type=\"button\" class=\"btnAddDelete\" value=\"Reset\"/>\n");
      out.write("                        </div>    \n");
      out.write("                         </form> \n");
      out.write("          </div>\n");
      out.write("\t\t</div> \n");
      out.write("            </div>\n");
      out.write("           <!-- fin chat request -->\n");
      out.write("           \n");
      out.write("           \n");
      out.write("             <div id=\"script\"></div> \n");
      out.write("            \n");
      out.write("            <script>!window.jQuery && document.write(unescape('%3Cscript src=\"js/jquery-1.7.1.min.js\"%3E%3C/script%3E'))</script>\n");
      out.write("            <script type=\"text/javascript\" src=\"js/demo.js\"></script>\n");
      out.write("            <script type=\"text/javascript\" src=\"js/scroll.js\"></script>\n");
      out.write("            \n");
      out.write("            \n");
      out.write("            <script type=\"text/javascript\" src=\"js/chat.js\"></script>   \n");
      out.write("          \n");
      out.write("            \n");
      out.write("            \n");
      out.write("            \n");
      out.write("            \n");
      out.write("            \n");
      out.write("            \n");
      out.write("            <script>\n");
      out.write("             var myUsers = setInterval(function(){javascript:getUsers('');},1000);\n");
      out.write("             \n");
      out.write("                    \n");
      out.write("                    function getUsers(message) {\n");
      out.write("                        $.ajax({\n");
      out.write("                        type: 'POST',\n");
      out.write("                        url: 'GetUsers.do',\n");
      out.write("                        data: {\n");
      out.write("                        message: message\n");
      out.write("                        }\n");
      out.write("                        }).done(function(resp){\n");
      out.write("                        $('#divUsers').html(resp);\n");
      out.write("                        });\n");
      out.write("                        }\n");
      out.write("                     function createSelecChat(){\n");
      out.write("                          $.ajax({\n");
      out.write("                            type:'POST',\n");
      out.write("                            url:'createSelecChat.do'\n");
      out.write("                            }).done(function(resp){\n");
      out.write("                            $('#areaUsers').html(resp);   \n");
      out.write("                           });\n");
      out.write("                     } \n");
      out.write("                     \n");
      out.write("                     function createSelecChatReq(){\n");
      out.write("                            $.ajax({\n");
      out.write("                            type:'POST',\n");
      out.write("                            url:'createSelecChatReq.do'\n");
      out.write("                            }).done(function(resp){\n");
      out.write("                            $('#areaChats').html(resp);   \n");
      out.write("                           });\n");
      out.write("                     }\n");
      out.write("                     \n");
      out.write("                     function acChatReq(nick,id) {\n");
      out.write("                        $.ajax({\n");
      out.write("                        type: 'POST',\n");
      out.write("                        url: 'acceptRequest.do',\n");
      out.write("                        data: {\n");
      out.write("                        nick: nick,\n");
      out.write("                        id: id\n");
      out.write("                        }\n");
      out.write("                        }).done(function(resp){\n");
      out.write("                        $('#F').html(resp);\n");
      out.write("                        });\n");
      out.write("                        }\n");
      out.write("                     \n");
      out.write("                     function Options(id){\n");
      out.write("                           $.ajax({\n");
      out.write("                            type: 'POST',\n");
      out.write("                            url: 'isHost.do',\n");
      out.write("                            data: {\n");
      out.write("                            id: id\n");
      out.write("                            }\n");
      out.write("                        }).done(function(resp){\n");
      out.write("                        $('#Options').html(resp);\n");
      out.write("                        });   \n");
      out.write("                        \n");
      out.write("                        type = $(this).attr('data-type');\n");
      out.write("\n");
      out.write("                               $('.overlay-contaoption').fadeIn(function() {\n");
      out.write("\n");
      out.write("                                       window.setTimeout(function(){\n");
      out.write("                                               $('.window-containeroption.'+type).addClass('window-containeroption-visible');\n");
      out.write("                                       }, 100);\n");
      out.write("\n");
      out.write("                               });\n");
      out.write("                     }\n");
      out.write("                     \n");
      out.write("                     function OptionsManager(id){\n");
      out.write("                         $.ajax({\n");
      out.write("                            type: 'GET',\n");
      out.write("                            url: 'OptionsManager.do',\n");
      out.write("                            data: {\n");
      out.write("                            id: id\n");
      out.write("                            }\n");
      out.write("                        }).done(function(resp){\n");
      out.write("                        $('#areaDelete').html(resp);\n");
      out.write("                        }); \n");
      out.write("                        \n");
      out.write("                          $.ajax({\n");
      out.write("                            type: 'POST',\n");
      out.write("                            url: 'OptionsManager.do',\n");
      out.write("                            data: {\n");
      out.write("                            id: id\n");
      out.write("                            }\n");
      out.write("                        }).done(function(resp){\n");
      out.write("                        $('#areaAdd').html(resp);\n");
      out.write("                        });  \n");
      out.write("                        \n");
      out.write("                    }\n");
      out.write("                /*    \n");
      out.write("                    function deleteChat(id){\n");
      out.write("                      $.ajax({\n");
      out.write("                        type: 'POST',\n");
      out.write("                        url: 'deleteChat.do',\n");
      out.write("                        data: {\n");
      out.write("                        id: id\n");
      out.write("                        }\n");
      out.write("                        }).done(function(resp){\n");
      out.write("                        $('#F').html(resp);\n");
      out.write("                        });  \n");
      out.write("                    }\n");
      out.write("                  */   \n");
      out.write("                     \n");
      out.write("                     \n");
      out.write("                     function closeOption(){\n");
      out.write("                         $('.closeAddDel').click(function() {\n");
      out.write("                        $('.overlay-contaoption').fadeOut().end().find('.window-containeroption').removeClass('window-containeroption-visible');\n");
      out.write("                          });\n");
      out.write("                     }\n");
      out.write("                     \n");
      out.write("                        var myInvitation = setInterval(function(){getInvitation('');},1000);\n");
      out.write("          \n");
      out.write("                        function getInvitation(message) {\n");
      out.write("                        $.ajax({\n");
      out.write("                        type: 'POST',\n");
      out.write("                        url: 'Invitation.do',\n");
      out.write("                        data: {\n");
      out.write("                        message: message\n");
      out.write("                        }\n");
      out.write("                        }).done(function(resp){\n");
      out.write("                        $('#divInvitation').html(resp);\n");
      out.write("                        });\n");
      out.write("                        }\n");
      out.write("                        \n");
      out.write("                       var myRequest = setInterval(function(){getRequest();},1000);\n");
      out.write("                        \n");
      out.write("                        function getRequest(){\n");
      out.write("                          $.ajax({\n");
      out.write("                        type: 'POST',\n");
      out.write("                        url: 'RequestChat.do',\n");
      out.write("                        \n");
      out.write("                        }).done(function(resp){\n");
      out.write("                        $('#divRequest').html(resp);\n");
      out.write("                        });  \n");
      out.write("                        }\n");
      out.write("            \n");
      out.write("                var myGroup = setInterval(function(){getMessagesG(1);},500);\n");
      out.write("          \n");
      out.write("                        function getMessagesG(id) {\n");
      out.write("                        $.ajax({\n");
      out.write("                        type: 'POST',\n");
      out.write("                        url: 'GetMessages.do',\n");
      out.write("                        data: {\n");
      out.write("                            id: id\n");
      out.write("                        }\n");
      out.write("                        }).done(function(resp){\n");
      out.write("                        $('#divChat').html(resp);\n");
      out.write("                        });\n");
      out.write("                        var objDiv = document.getElementById(\"divChat\");\n");
      out.write("                    \n");
      out.write("                        objDiv.scrollTop = objDiv.scrollHeight;\n");
      out.write("                        }\n");
      out.write("                        \n");
      out.write("                        function saveValue(R){\n");
      out.write("                          var aux= parseInt(R.toString().localeCompare(\"\"));\n");
      out.write("                          \n");
      out.write("                          if(aux<0 || aux>0){\n");
      out.write("                            var x = document.getElementById(\"MG\").value;\n");
      out.write("                            document.getElementById(\"MG\").value = \"\";\n");
      out.write("                            sendMessage(1,x);\n");
      out.write("                            }\n");
      out.write("                        }\n");
      out.write("                        \n");
      out.write("                        function sendMessage(id, message) {\n");
      out.write("                        $.ajax({\n");
      out.write("                        type:'POST',\n");
      out.write("                        url: 'SendMessage.do',\n");
      out.write("                        data: {\n");
      out.write("                        message: message, id: id\n");
      out.write("                        }\n");
      out.write("                        }).done(function(resp){\n");
      out.write("                        $('#none').html(resp);\n");
      out.write("                        });\n");
      out.write("                        }\n");
      out.write("                        \n");
      out.write("                       \n");
      out.write("                        \n");
      out.write("                       \n");
      out.write("                        function getScript(id) {\n");
      out.write("                        $.ajax({\n");
      out.write("                        type: 'POST',\n");
      out.write("                        url: 'createScript.do',\n");
      out.write("                        data: {\n");
      out.write("                        id: id\n");
      out.write("                        }\n");
      out.write("                        }).done(function(resp){\n");
      out.write("                        $('#script').html(resp);\n");
      out.write("                        });\n");
      out.write("                        }\n");
      out.write("                        \n");
      out.write("                        \n");
      out.write("                        function alphaOnly(event) {\n");
      out.write("                            var key = event.keyCode;\n");
      out.write("                            return ((key >= 65 && key <= 90) || key == 8);\n");
      out.write("                        };\n");
      out.write("                 </script>\n");
      out.write("                       \n");
      out.write("            \n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
