/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2015-04-13 14:17:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class interfaz_005fVendedor_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

 String User;
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!doctype html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("\t<meta charset=\"utf-8\"/>\n");
      out.write("\t<title>Phonebook</title>\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"view/css/layout.css\" type=\"text/css\" media=\"screen\" />\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"view/css/chat.css\" type=\"text/css\" media=\"screen\" />\n");
      out.write("\t<script src=\"view/js/jquery-1.5.2.min.js\" type=\"text/javascript\"></script>\n");
      out.write("\t<script src=\"view/js/hideshow.js\" type=\"text/javascript\"></script>\n");
      out.write("\t<script src=\"view/js/jquery.tablesorter.min.js\" type=\"text/javascript\"></script>\n");
      out.write("\t<script type=\"text/javascript\" src=\"view/js/jquery.equalHeight.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"view/js/InterfazVendedor.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write("\t$(document).ready(function() \n");
      out.write("    \t{ \n");
      out.write("      \t  $(\".tablesorter\").tablesorter(); \n");
      out.write("   \t } \n");
      out.write("\t);\n");
      out.write("\t$(document).ready(function() {\n");
      out.write("\n");
      out.write("\t//When page loads...\n");
      out.write("\t$(\".tab_content\").hide(); //Hide all content\n");
      out.write("\t$(\"ul.tabs li:first\").addClass(\"active\").show(); //Activate first tab\n");
      out.write("\t$(\".tab_content:first\").show(); //Show first tab content\n");
      out.write("\n");
      out.write("\t//On Click Event\n");
      out.write("\t$(\"ul.tabs li\").click(function() {\n");
      out.write("\n");
      out.write("\t\t$(\"ul.tabs li\").removeClass(\"active\"); //Remove any \"active\" class\n");
      out.write("\t\t$(this).addClass(\"active\"); //Add \"active\" class to selected tab\n");
      out.write("\t\t$(\".tab_content\").hide(); //Hide all tab content\n");
      out.write("\n");
      out.write("\t\tvar activeTab = $(this).find(\"a\").attr(\"href\"); //Find the href attribute value to identify the active tab + content\n");
      out.write("\t\t$(activeTab).fadeIn(); //Fade in the active ID content\n");
      out.write("\t\treturn false;\n");
      out.write("\t});\n");
      out.write("\n");
      out.write("});\n");
      out.write("    </script>\n");
      out.write("    <script type=\"text/javascript\">\n");
      out.write("    $(function(){\n");
      out.write("        $('.column').equalHeight();\n");
      out.write("    });\n");
      out.write("</script>\n");
      out.write(" ");
      out.write("\n");
      out.write("    ");

        if(session.getAttribute("sesion_usuario")==null){
       response.sendRedirect("login.jsp");
         }else{
            User = (String)session.getAttribute("sesion_usuario");
        }
    
      out.write("\n");
      out.write("<body onload=\"iniciar('");
      out.print(User);
      out.write("')\">\n");
      out.write("   \n");
      out.write("\t<header id=\"header\">\n");
      out.write("\t\t<hgroup>\n");
      out.write("\t\t\t<h1 class=\"site_title\"><a href=\"index.html\"><img src=\"images/phonebookLogo1.png\" width=\"343\" height=\"80\"></a></h1>\n");
      out.write("                        <h2 class=\"section_title\"><!--texto --></h2><div class=\"btn_view_site\"><a href=\"#\"><img src=\"images/icn_profile.png\" width=\"20\" height=\"20\" style=\"margin-right: 5px;\"><div id=\"vendedor1\">");
      out.print(User);
      out.write("</div></a></div>\n");
      out.write("\t\t</hgroup>\n");
      out.write("\t</header> <!-- end of header bar -->\n");
      out.write("\t\n");
      out.write("  <section id=\"secondary_bar\">\n");
      out.write("\t\t<div class=\"user\">\n");
      out.write("\t\t \n");
      out.write("\t\t\t<!-- <a class=\"logout_user\" href=\"#\" title=\"Logout\">Logout</a> -->\n");
      out.write("\t</div>\n");
      out.write("\t\t<div class=\"breadcrumbs_container\">\n");
      out.write("\t\t\n");
      out.write("\t</div>\n");
      out.write("\t</section><!-- end of secondary bar -->\n");
      out.write("\t\n");
      out.write("\t<aside id=\"sidebar\" class=\"column\">\n");
      out.write("\t\t<h2>Menú</h2>\n");
      out.write("\t\t<hr/>\n");
      out.write("\t\t<h3>Compras</h3>\n");
      out.write("\t\t<ul class=\"toggle\">\n");
      out.write("\t\t\t<li class=\"icn_categories\"><a href=\"http://localhost:8080/PhoneBook/interfaz_comprador.jsp\">Publicaciones</a></li>\n");
      out.write("\t\t\t\n");
      out.write("\t\t</ul>\n");
      out.write("\t\t<h3>Ventas</h3>\n");
      out.write("        \n");
      out.write("        \n");
      out.write("        \t<ul class=\"toggle\">\n");
      out.write("\t\t\t<li class=\"icn_categories\"><a href=\"http://localhost:8080/PhoneBook/interfaz_Vendedor.jsp\">Mis Publicaciones</a></li>\n");
      out.write("            <li class=\"icn_new_article\"><a href=\"http://localhost:8080/PhoneBook/interfaz_Vendedor_crearAnuncio.jsp\">Crear Publicacion</a></li>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t</ul>\n");
      out.write("\t\n");
      out.write("\n");
      out.write("\t</aside><!-- end of sidebar -->\n");
      out.write("\t\n");
      out.write("\t<section id=\"main\" class=\"column\">\n");
      out.write("            ");

              if(request.getAttribute("message")!=null){
                  out.println("<h4 class='alert_success'>"+request.getAttribute("message")+"</h4>");
              }else{
                  out.println("<h4 class='alert_info'>Bienvenido a PhoneBook</h4>");
              }  
            
      out.write("\n");
      out.write("\t\t\n");
      out.write("\t\t<article class=\"module width_3_quarter\">\n");
      out.write("\t\t<header><h3 class=\"tabs_involved\">Mis Publicaciones</h3>\n");
      out.write("\t\t</header>\n");
      out.write("\n");
      out.write("\t\t<div class=\"tab_container\" >\n");
      out.write("\t\t\t<div id=\"tab1\" class=\"tab_content\">\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t</div><!-- end of #tab1 -->\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t</div><!-- end of .tab_container -->\n");
      out.write("\t\t\n");
      out.write("\t\t</article><!-- end of content manager article -->\n");
      out.write("\t\n");
      out.write("\t\t<article class=\"module width_quarter\">\n");
      out.write("\t\t\t<header><h3>Clientes</h3></header>\n");
      out.write("\t\t\t<div class=\"message_list\" >\n");
      out.write("                            <div class=\"module_content\" id=\"showChats\">\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t</article>\n");
      out.write("                \n");
      out.write("                \n");
      out.write("                <article class=\"module width_quarter\">\n");
      out.write("\t\t\t<header><h3 id=\"thisCliente\"> </h3></header>\n");
      out.write("                        <div class=\"message_list\" style=\"height: 250px;\">\n");
      out.write("                            <table><tr><td> <div id=\"chatVendedor\" style=\"height: 210px; overflow-y: auto;\"></div></td></tr><tr><td><input id=\"textoMsj\" type=\"text\" size=\"35\" placeholder=\"Escribe mensaje\" onkeydown=\"enviaMsj('");
      out.print(User);
      out.write("',event)\"/></td></tr></table>\n");
      out.write("\t\t\t\n");
      out.write("                            <div class=\"module_content\" >\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t</article>\n");
      out.write("                \n");
      out.write("                <!-- end of messages article -->\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t</section>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t<footer>\n");
      out.write("\t\t\t<p><strong>Copyright &copy; 2015 Phonebook</strong></p>\n");
      out.write("\t\t\t\n");
      out.write("\t\t</footer>\n");
      out.write("\t\t  <script type=\"text/javascript\" src=\"view/js/chat.js\"></script>   \n");
      out.write("          \n");
      out.write("</body>\n");
      out.write("<script>\n");
      out.write("           var inicio = getPublicaciones('');\n");
      out.write("           var misPublicaciones = setInterval(function(){javascript:getPublicaciones('');},1500);  \n");
      out.write("                    \n");
      out.write("                    function getPublicaciones(message) {\n");
      out.write("                        $.ajax({\n");
      out.write("                        type: 'GET',\n");
      out.write("                        url: 'Editar_listar_publicaciones.do',\n");
      out.write("                        data: {\n");
      out.write("                        message: message\n");
      out.write("                        }\n");
      out.write("                        }).done(function(resp){\n");
      out.write("                        $('#tab1').html(resp);\n");
      out.write("                        });\n");
      out.write("                        }\n");
      out.write("                    \n");
      out.write("                    function eliminar_publicacion(id) {\n");
      out.write("                        $.ajax({\n");
      out.write("                        type: 'GET',\n");
      out.write("                        url: 'Crear_eliminar_publicacion.do',\n");
      out.write("                        data: {\n");
      out.write("                        id: id\n");
      out.write("                        }\n");
      out.write("                        }).done(function(resp){\n");
      out.write("                        $('#X').html(resp);\n");
      out.write("                        });\n");
      out.write("                        }    \n");
      out.write("                        \n");
      out.write("                        \n");
      out.write("                   function redireccion(x){\n");
      out.write("                       window.location=\"http://localhost:8080/PhoneBook/interfaz_Vendedor_editaAnuncio.jsp?id=\"+x;\n");
      out.write("                   }     \n");
      out.write("                   \n");
      out.write("                   function sendMessage2(){\n");
      out.write("    \n");
      out.write(" }\n");
      out.write("    \n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
