/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2015-04-13 11:15:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.ResultSet;
import BaseDatos.AdministradorBD;

public final class interfaz_005fcomprador_005fanuncio_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

 String User;
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"utf-8\"/>\r\n");
      out.write("\t<title>Phonebook</title>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"view/css/layout.css\" type=\"text/css\" media=\"screen\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"view/css/chat.css\" type=\"text/css\" media=\"screen\" />\r\n");
      out.write("\t<script src=\"view/js/jquery-1.5.2.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"view/js/hideshow.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"view/js/jquery.tablesorter.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"view/js/jquery.equalHeight.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"view/js/InterfazComprador.js\"></script>\r\n");
      out.write("        <script type=\"text/javascript\">\r\n");
      out.write("            \r\n");
      out.write("\t$(document).ready(function() \r\n");
      out.write("    \t{ \r\n");
      out.write("      \t  $(\".tablesorter\").tablesorter(); \r\n");
      out.write("   \t } \r\n");
      out.write("\t);\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\r\n");
      out.write("\t//When page loads...\r\n");
      out.write("\t$(\".tab_content\").hide(); //Hide all content\r\n");
      out.write("\t$(\"ul.tabs li:first\").addClass(\"active\").show(); //Activate first tab\r\n");
      out.write("\t$(\".tab_content:first\").show(); //Show first tab content\r\n");
      out.write("\r\n");
      out.write("\t//On Click Event\r\n");
      out.write("\t$(\"ul.tabs li\").click(function() {\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"ul.tabs li\").removeClass(\"active\"); //Remove any \"active\" class\r\n");
      out.write("\t\t$(this).addClass(\"active\"); //Add \"active\" class to selected tab\r\n");
      out.write("\t\t$(\".tab_content\").hide(); //Hide all tab content\r\n");
      out.write("\r\n");
      out.write("\t\tvar activeTab = $(this).find(\"a\").attr(\"href\"); //Find the href attribute value to identify the active tab + content\r\n");
      out.write("\t\t$(activeTab).fadeIn(); //Fade in the active ID content\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("    </script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    $(function(){\r\n");
      out.write("        $('.column').equalHeight();\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    ");

        if(session.getAttribute("sesion_usuario")==null){
       response.sendRedirect("login.jsp");
         }else{
            User = (String)session.getAttribute("sesion_usuario");
        }
    
      out.write("\r\n");
      out.write("    \r\n");
      out.write("     ");

        String id = request.getParameter("id");
            AdministradorBD admi = new AdministradorBD();
            ResultSet rs = admi.Ver_info(id);
           rs.next();
            String titulo = rs.getString("titulo");
            int Precio = rs.getInt("Precio");
            String Descripcion = rs.getString("Descripcion");
            String usuario = rs.getString("Usuario");
            String urlImage = "Img_2.jpg";
            
           String modelo = rs.getString("nombremodelo");
           int precionuevo = rs.getInt("PrecioNuevo");
           String sistema = rs.getString("SisOperativo");
           int camara = rs.getInt("Camara");
           String resolucion = rs.getString("ResolucionC");
           String memoria = rs.getString("MemoriaInterna");
                  
            String marca = rs.getString("nombremarca");
            
         
      out.write("\r\n");
      out.write("\t<header id=\"header\">\r\n");
      out.write("\t\t<hgroup>\r\n");
      out.write("\t\t\t<h1 class=\"site_title\"><a href=\"index.html\"><img src=\"images/phonebookLogo1.png\" width=\"343\" height=\"80\"></a></h1>\r\n");
      out.write("                        <h2 class=\"section_title\"><!--texto --></h2><div class=\"btn_view_site\"><a href=\"#\"><img src=\"images/icn_profile.png\" width=\"20\" height=\"20\" style=\"margin-right: 5px;\"><div id=\"comprador\">");
      out.print(User);
      out.write("</div></a></div>\r\n");
      out.write("\t\t</hgroup>\r\n");
      out.write("\t</header> <!-- end of header bar -->\r\n");
      out.write("\t\r\n");
      out.write("  <section id=\"secondary_bar\">\r\n");
      out.write("\t\t<div class=\"user\">\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t\t<!-- <a class=\"logout_user\" href=\"#\" title=\"Logout\">Logout</a> -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t<div class=\"breadcrumbs_container\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</section><!-- end of secondary bar -->\r\n");
      out.write("\t\r\n");
      out.write("\t<aside id=\"sidebar\" class=\"column\">\r\n");
      out.write("\t\t<h2>Menú</h2>\r\n");
      out.write("\t\t<hr/>\r\n");
      out.write("\t\t<h3>Compras</h3>\r\n");
      out.write("\t\t<ul class=\"toggle\">\r\n");
      out.write("\t\t\t<li class=\"icn_categories\"><a href=\"interfaz_comprador.jsp\">Publicaciones</a></li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<h3>Ventas</h3>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \t<ul class=\"toggle\">\r\n");
      out.write("\t\t\t<li class=\"icn_categories\"><a href=\"interfaz_Vendedor.jsp\">Mis Publicaciones</a></li>\r\n");
      out.write("            <li class=\"icn_new_article\"><a href=\"interfaz_Vendedor_crearAnuncio.jsp\">Crear Publicacion</a></li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t</aside><!-- end of sidebar -->\r\n");
      out.write("\t\r\n");
      out.write("\t<section id=\"main\" class=\"column\">\r\n");
      out.write("            ");

              if(request.getAttribute("message")!=null){
                  out.println("<h4 class='alert_success'>"+request.getAttribute("message")+"</h4>");
              }else{
                  out.println("<h4 class='alert_info'>Bienvenido a PhoneBook</h4>");
              }  
            
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<article class=\"module width_3_quarter\">\r\n");
      out.write("\t\t<header><h3 class=\"tabs_involved\">Publicacion de ");
      out.print(usuario);
      out.write("</h3>\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"tab_container\" >\r\n");
      out.write("\t\t\t<div id=\"tab1\" class=\"tab_content\">\r\n");
      out.write("\t\t\t\t<form class=\"contact_form\" action=\"Ver_Publicacion.do\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("                                  \r\n");
      out.write("                                    <section style=\"margin-left: 250px; font-size: 20px; margin-top: 20px;\">\r\n");
      out.write("                                        <label style=\"color: rgb(145,186,188);\"><strong>");
      out.print(titulo);
      out.write("</strong></label> \r\n");
      out.write("                                       </section>\r\n");
      out.write("                                        <section>\r\n");
      out.write("                                        <input style=\"margin-left: 190px; margin-top: 20px; border-radius:5px;\" width=\"250px\" height=\"250px\" type=\"image\" src=\"BDImagenes_Usuarios/");
      out.print(urlImage);
      out.write("\" title=\"MaxImg\"/>\r\n");
      out.write("                                    </section>\r\n");
      out.write("                                    \r\n");
      out.write("                                      <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <div class=\"wrapper\">\r\n");
      out.write("                <div id=\"st-accordion\" class=\"st-accordion\">\r\n");
      out.write("                    <ul><br>\r\n");
      out.write("                        <hr><center><li>\r\n");
      out.write("                            <a href=\"#\">MARCA<span ></span></a><br>\r\n");
      out.write("                            <div class=\"st-content\"style=\"text-align: left; margin-left: 150px;\">\r\n");
      out.write("                                <ul><br>\r\n");
      out.write("                                    <li>Nombre de la marca: <strong>");
      out.print(marca);
      out.write("</strong></li>\r\n");
      out.write("                                     \r\n");
      out.write("                                    \r\n");
      out.write("                                </ul>\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                            </li></center>\r\n");
      out.write("                                    <hr><center> <li>\r\n");
      out.write("                       <a href=\"#\">MODELO<span ></span></a>\r\n");
      out.write("                            <div class=\"st-content\"style=\"text-align: left; margin-left: 150px;\" >\r\n");
      out.write("                                <ul><br>\r\n");
      out.write("                                    <li>Nombre del modelo: <strong>");
      out.print(modelo);
      out.write("</strong></li><br>\r\n");
      out.write("                                    <li>Nuevo precio: <strong>$");
      out.print(precionuevo);
      out.write("</strong></li><br>\r\n");
      out.write("                                    <li>Sistema operativo: <strong>");
      out.print(sistema);
      out.write("</strong></li><br>\r\n");
      out.write("                                  ");

                                             if(camara==1){
                                              out.println("<li>Cuenta con camara: <strong>Si</strong></li><br>");
                                             }else
                                                  out.println("<li>Cuenta con camara: <strong>No</strong></li><br>");
                                             
      out.write("\r\n");
      out.write("                                    <li>Resolución de camara: <strong>");
      out.print(resolucion);
      out.write("</strong></li><br>\r\n");
      out.write("                                    <li>Memoria Interna: <strong>");
      out.print(memoria);
      out.write("</strong></li><br>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                               \r\n");
      out.write("                                <br>\r\n");
      out.write("                            </div>\r\n");
      out.write("                       <hr> </li></center>\r\n");
      out.write("                                <center><li>\r\n");
      out.write("                            <a href=\"#\">DATOS DE LA PUBLICACION<span ></span></a>\r\n");
      out.write("                            <div class=\"st-content\" style=\"text-align: left; margin-left: 150px;\">\r\n");
      out.write("                                <ul><br>\r\n");
      out.write("                                    <li>Precio de publicación: <strong>$");
      out.print(Precio);
      out.write("</strong></li><br>\r\n");
      out.write("                                    <li>Descripcion del celular: <strong>");
      out.print(Descripcion);
      out.write("</strong></li><br>\r\n");
      out.write("                                    <li>Nombre del vendedor: <strong><div id=\"vendedor\">");
      out.print(usuario);
      out.write("</div></strong></li><br>\r\n");
      out.write("                                    \r\n");
      out.write("                                </ul>\r\n");
      out.write("                                         <br><br>\r\n");
      out.write("                            </div>\r\n");
      out.write("                                    </li></center>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("                                    \r\n");
      out.write("                                    \r\n");
      out.write("                                    \r\n");
      out.write("                                       \r\n");
      out.write("                                </form>\r\n");
      out.write("                                           \r\n");
      out.write("                                                                 \r\n");
      out.write("                                            <section style=\"margin-left: 200px;\">\r\n");
      out.write("                                                \r\n");
      out.write("                                            \r\n");
      out.write("                                            <button onClick=\"mailsome1()\">Enviar Correo</button>\r\n");
      out.write("                                            <button onClick=\"iniciarChat('");
      out.print(User);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(usuario);
      out.write("')\">Iniciar Chat</button>\r\n");
      out.write("                                            </section>\r\n");
      out.write("                                                <br><br><br>\r\n");
      out.write("\t\t\t</div><!-- end of #tab1 -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div><!-- end of .tab_container -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</article><!-- end of content manager article -->\r\n");
      out.write("\t\r\n");
      out.write("                <article class=\"module width_quarter\" style=\"visibility: hidden; \" id=\"chatArea\">\r\n");
      out.write("\t\t\t<header><h3>Chat</h3></header>\r\n");
      out.write("                        <table><tr ><td><div id=\"chatComprador\" style=\"height: 300px; overflow-y: auto;\"></div></td></tr><tr><td><input id=\"textoMsj\" type=\"text\" size=\"35\" placeholder=\"Escribe mensaje\" onKeyDown=\"enviaMsj('");
      out.print(User);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(usuario );
      out.write("',event)\"/></td></tr></table>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</article><!-- end of messages article -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<footer>\r\n");
      out.write("\t\t\t<p><strong>Copyright &copy; 2015 Phonebook</strong></p>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("\t\t  <script type=\"text/javascript\" src=\"view/js/chat.js\"></script>   \r\n");
      out.write("                  \r\n");
      out.write("                \r\n");
      out.write("          \r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("    var mailsys=\"Netscape mail\";\r\n");
      out.write("    var author=\"Dagoberto\";\r\n");
      out.write("\r\n");
      out.write("                    if (author == \"Dagoberto\"){\r\n");
      out.write("                            phrompt=prompt;\r\n");
      out.write("                            snarkconf=confirm;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    function mailsome1(id){\r\n");
      out.write("                                user=phrompt(\"La dirección e-mail es : \",\"nombre_correo@gmail.com\");\r\n");
      out.write("                                msg=phrompt(\"Ingresa el asunto del mensaje: \",\"Nombre del asunto\");\r\n");
      out.write("                                if (snarkconf(\"¿Estás seguro de querer enviar un mensaje a \"+id+\" con el siguiente asunto? \"+msg+\"?\")==true){\r\n");
      out.write("                                        parent.location.href='mailto:'+user+'?subject='+msg+'';\r\n");
      out.write("                                }         }            \r\n");
      out.write("                                \r\n");
      out.write("                       function getId(idPublicaciones){\r\n");
      out.write("                           $.ajax({\r\n");
      out.write("                        type: 'POST',\r\n");
      out.write("                        url: 'Ver_Referencia.do',\r\n");
      out.write("                        data: {\r\n");
      out.write("                        idPublicaciones: idPublicaciones\r\n");
      out.write("                        }\r\n");
      out.write("                        }).done(function(resp){\r\n");
      out.write("                        $('#sel_modelo').html(resp);\r\n");
      out.write("                        });\r\n");
      out.write("                           \r\n");
      out.write("                       }\r\n");
      out.write("                       \r\n");
      out.write("                      \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
